export var currentLevel = [{x : null, y : null, width : null, height : null, type : null, state : null}];
export var nonPlayerCharacters = [{x : null, y : null, type : null, state : null}];
export var enemies = [{x : null, y : null, type : null}];
export var levelForeground = {spritex : null, spritey : null};
export var levelBackground = {spritex : null, spritey : null};

export function defineLevel(level) {
  switch(level) {
    case 1 :
        // blue print for levels
        levelForeground.spritey = 0;
        levelForeground.spritex = 0;
        levelBackground.spritey = 0;
        levelBackground.spritex = 0;
        nonPlayerCharacters[0].x = 0;
        nonPlayerCharacters[0].y = 0;
        nonPlayerCharacters[0].type = 0;
        nonPlayerCharacters[0].state = 0;
        nonPlayerCharacters[1].x = 0;
        nonPlayerCharacters[1].y = 0;
        nonPlayerCharacters[1].type = 0;
        nonPlayerCharacters[1].state = 0;
        enemies[0].x = 0;
        enemies[0].y = 0;
        enemies[0].type = 0;
        enemies[1].x = 0;
        enemies[1].y = 0;
        enemies[1].type = 0;
        enemies[2].x = 0;
        enemies[2].y = 0;
        enemies[2].type = 0;
        enemies[3].x = 0;
        enemies[3].y = 0;
        enemies[3].type = 0;
        enemies[4].x = 0;
        enemies[4].y = 0;
        enemies[4].type = 0;
        currentLevel[0].x = 0;
        currentLevel[0].y = 0;
        currentLevel[0].width = 0;
        currentLevel[0].height = 0;
        currentLevel[0].type = 0;
        currentLevel[0].state = 0;
        currentLevel[1].x = 0;
        currentLevel[1].y = 0;
        currentLevel[1].width = 0;
        currentLevel[1].height = 0;
        currentLevel[1].type = 0;
        currentLevel[1].state = 0;
        currentLevel[2].x = 0;
        currentLevel[2].y = 0;
        currentLevel[2].width = 0;
        currentLevel[2].height = 0;
        currentLevel[2].type = 0;
        currentLevel[2].state = 0;
        currentLevel[3].x = 0;
        currentLevel[3].y = 0;
        currentLevel[3].width = 0;
        currentLevel[3].height = 0;
        currentLevel[3].type = 0;
        currentLevel[3].state = 0;
        currentLevel[4].x = 0;
        currentLevel[4].y = 0;
        currentLevel[4].width = 0;
        currentLevel[4].height = 0;
        currentLevel[4].type = 0;
        currentLevel[4].state = 0;
        currentLevel[5].x = 0;
        currentLevel[5].y = 0;
        currentLevel[5].width = 0;
        currentLevel[5].height = 0;
        currentLevel[5].type = 0;
        currentLevel[5].state = 0;
        currentLevel[6].x = 0;
        currentLevel[6].y = 0;
        currentLevel[6].width = 0;
        currentLevel[6].height = 0;
        currentLevel[6].type = 0;
        currentLevel[6].state = 0;
        break;
      default : defineLevel(1);
    };
    return;
};
